### ISSUE TITLE
dd() in release

### ISSUE THREAD

**Issue by Nuranto** [RyanDaDeng/laravel-google-recaptcha-v2#7]
See : https://github.com/RyanDaDeng/laravel-google-recaptcha-v2/blob/a5b94ed83a97a798c3472f84be1cd9817a3a8be2/src/Validations/GoogleReCaptchaV2ValidationRule.php#L31

**Comment by Nuranto** [comment]
Other bugs : 
https://github.com/RyanDaDeng/laravel-google-recaptcha-v2/blob/a5b94ed83a97a798c3472f84be1cd9817a3a8be2/src/Core/CurlRequestClient.php#L28

https://github.com/RyanDaDeng/laravel-google-recaptcha-v2/blob/a5b94ed83a97a798c3472f84be1cd9817a3a8be2/src/Core/GuzzleRequestClient.php#L30

Is this lib actually finished ? And will it be maintained ?

**Comment by RyanDaDeng** [comment]
@Nuranto Good point...This library is just branched out from my v3. Yeah, I will fix it up tonight.

**Comment by Nuranto** [comment]
Ok, Thanks @RyanDaDeng  !

**Comment by RyanDaDeng** [comment]
@Nuranto I have fixed the mentioned bugs. By the way, I will be polishing it up this weekend. I think the current version is production-ready. However, I will do an audit by this week.

**Comment by RyanDaDeng** [comment]
@Nuranto By the way, I am planning to do more open source projects but stuck on the ideas at the moment. If you got any ideas that could benefit people, let me know if I can help anything on it. Thanks.

**Comment by Nuranto** [comment]
Thank you for all @RyanDaDeng !
For ideas of new project, I don't know at the moment, but I will tell you if an idea emerge.
For existing projects, I see recently they were looking for someone to takover : https://github.com/proengsoft/laravel-jsvalidation/issues/376

**Comment by Nuranto** [comment]
Oh, there is something... There is no CRUD grid with full functionnalities out there.
I'm using leantony/laravel-grid for a project, which is good and do the basic job. But it lacks many functionnalities and customization possibilities (for instance bulk actions). There are other libs, but same issue. The most full grid system I ever tested was the magento's one, but there is no standalone package of it, it is not independent.
I think it could be useful to a lot, but it is not a small project...

**Comment by RyanDaDeng** [comment]
> Oh, there is something... There is no CRUD grid with full functionnalities out there.
> I'm using leantony/laravel-grid for a project, which is good and do the basic job. But it lacks many functionnalities and customization possibilities (for instance bulk actions). There are other libs, but same issue. The most full grid system I ever tested was the magento's one, but there is no standalone package of it, it is not independent.
> I think it could be useful to a lot, but it is not a small project...

This sounds like Laravel Nova project, however, it's commercial paid product implemented by Laravel author built on top of vuejs and it's a data-driven approach.

**Comment by RyanDaDeng** [comment]
@Nuranto Thanks for telling me about it. Yeah, I will take a deep look into those projects this weekend.

**Comment by Nuranto** [comment]
> This sounds like Laravel Nova project, however, it's commercial paid product implemented by Laravel author built on top of vuejs and it's a data-driven approach.

Oh, I wasn't aware of this. I will dig up in there, seems interesting indeed.

**Comment by RyanDaDeng** [comment]
> > This sounds like Laravel Nova project, however, it's commercial paid product implemented by Laravel author built on top of vuejs and it's a data-driven approach.
> 
> Oh, I wasn't aware of this. I will dig up in there, seems interesting indeed.

There is a Laravel Event video in youtube about Nova, you can search for that. The Nova is more like another Wordpress admin portal with integrations on Eloquent model.
